spring:
  application:
    name: sb-prueba-service  
  
server:
  port: 1218
  
jwt:
  secret: password
 
#DETALLES DE LOGGING PARA ARCHIVOS Y NIVELES DE  ERROR#
logging:
  level:
    root: WARN
    mx.company.code : DEBUG    
    org:
      springframework:
        security: WARN
        web : ERROR
        web.servlet.DispatcherServlet: WARN #FOR SPRING CLOUD SLEUTH    
      hibernate: WARN        
      apache:
        commons:
          dbcp2: WARN  
  file: /Proyectos/Prueba/JavaWorkSpace/mx.company.code/log/${spring.application.name}ABC3.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger [%file:%line] - %msg%n'
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){magenta} %clr(%-5level) %clr([%thread]){blue} %clr(%logger) %clr([%file:%line]) - %msg%n'